name: Simple CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: student@iitm.ac.in
        run: echo "Hello from student@iitm.ac.in"
      
      - name: Success message
        run: echo "Workflow completed successfully!"
